---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-firefly-iii"
  ADDON_SLUG: "firefly-iii"
  ADDON_TARGET: "firefly-iii"
  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/debian-base:2.0.0"
  ADDON_AMD64_BASE: "hassioaddons/debian-base:2.0.0"
  ADDON_ARMHF_BASE: "hassioaddons/debian-base:2.0.0"
  ADDON_ARMV7_BASE: "hassioaddons/debian-base:2.0.0"
  ADDON_I386_BASE: "hassioaddons/debian-base:2.0.0"
